// bmi.js - BMI Calculator, Tips Toggle, and Downloads
document.addEventListener("DOMContentLoaded", () => {
  const bmiForm = document.getElementById("bmi-form");
  if (!bmiForm) return;

  const resultContainer = document.getElementById("result-container");
  const resultBadge = document.getElementById("result-badge");
  const resultText = document.getElementById("result-text");
  const progressBar = document.getElementById("progress-bar");
  const suggestionBox = document.getElementById("suggestion-box");
  const suggestionTitle = document.getElementById("suggestion-title");
  const suggestionList = document.getElementById("suggestion-list");
  const toggleBtn = document.getElementById("toggle-suggestions");
  const toggleIcon = document.getElementById("toggle-icon");

  const downloadButtons = document.getElementById("download-buttons");
  const downloadReport = document.getElementById("download-report");
  const downloadTracker = document.getElementById("download-tracker");
  const downloadDiet = document.getElementById("download-diet");

  const tips = {
    "Underweight": {
      color: "#fbbf24",
      list: [
        "Add calorie-dense, nutritious foods.",
        "Eat small meals more frequently.",
        "Incorporate strength training."
      ]
    },
    "Normal weight": {
      color: "#22c55e",
      list: [
        "Maintain a balanced diet with whole foods.",
        "Stay active 150+ minutes/week.",
        "Keep tracking your progress."
      ]
    },
    "Overweight": {
      color: "#f97316",
      list: [
        "Focus on portion control and whole foods.",
        "Add regular cardio and resistance training.",
        "Limit sugary drinks and ultra-processed foods."
      ]
    },
    "Obesity": {
      color: "#ef4444",
      list: [
        "Adopt a sustainable calorie deficit.",
        "Increase daily movement and structured exercise.",
        "Consult a healthcare professional."
      ]
    }
  };

  let lastBMI = null;
  let lastCategory = null;

  // ✅ BMI calculation
  bmiForm.addEventListener("submit", (e) => {
    e.preventDefault();
    const height = parseFloat(document.getElementById("height").value);
    const weight = parseFloat(document.getElementById("weight").value);

    if (height > 0 && weight > 0) {
      const h = height / 100;
      const bmi = +(weight / (h * h)).toFixed(2);
      let category = '';
      if (bmi < 18.5) category = 'Underweight';
      else if (bmi < 25) category = 'Normal weight';
      else if (bmi < 30) category = 'Overweight';
      else category = 'Obesity';

      lastBMI = bmi;
      lastCategory = category;

      resultContainer.style.display = "block";
      resultBadge.textContent = category;
      resultBadge.style.background = tips[category].color;
      resultBadge.style.color = "white";
      resultText.textContent = `Your BMI is ${bmi}`;

      progressBar.style.width = Math.min((bmi / 40) * 100, 100) + "%";
      progressBar.style.background = tips[category].color;

      suggestionBox.style.display = 'block';
      suggestionList.style.display = 'none';
      toggleIcon.textContent = '▼';
      suggestionBox.style.background = tips[category].color;
      suggestionBox.style.color = category === "Underweight" ? "#222" : "white";
      suggestionTitle.style.color = category === "Underweight" ? "#222" : "white";
      suggestionList.innerHTML = tips[category].list.map(t => `<li>${t}</li>`).join('');

      if (downloadButtons) downloadButtons.style.display = "block";
    } else {
      resultText.textContent = 'Please enter valid height and weight!';
      resultText.style.color = '#ef4444';
      resultContainer.style.display = "none";
      suggestionBox.style.display = 'none';
      if (downloadButtons) downloadButtons.style.display = "none";
    }
  });

  // ✅ Toggle suggestions
  if (toggleBtn) {
    toggleBtn.addEventListener("click", () => {
      if (suggestionList.style.display === "none") {
        suggestionList.style.display = "block";
        toggleIcon.textContent = '▲';
      } else {
        suggestionList.style.display = "none";
        toggleIcon.textContent = '▼';
      }
    });
  }

  // ======================
  // ✅ PDF REPORT HANDLERS
  // ======================

  function addHeaderFooter(doc, title) {
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(44, 62, 80);
    doc.text("GYM‖BMI", 20, 15, { align: "left" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(title, 105, 15, { align: "center" });

    const now = new Date().toLocaleString();
    doc.setFontSize(10);
    doc.text(`Generated: ${now}`, 200, 15, { align: "right" });

    doc.setDrawColor(150);
    doc.line(20, 20, 190, 20);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
      "Confidential | Generated by BMI Calculator – GYM‖BMI",
      105,
      285,
      { align: "center" }
    );
    doc.setTextColor(0);
  }

  // 1. BMI Report PDF (with Report Table instead of Chart)
  if (downloadReport) {
    downloadReport.addEventListener("click", () => {
      if (!lastBMI || !lastCategory) return alert("Please calculate BMI first!");

      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      addHeaderFooter(doc, "BMI Health Report");

      // Personal Details
      doc.setFontSize(12);
      const heightVal = document.getElementById("height").value;
      const weightVal = document.getElementById("weight").value;
      doc.text(`Height: ${heightVal} cm`, 20, 40);
      doc.text(`Weight: ${weightVal} kg`, 20, 48);

      // BMI Report Table
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("BMI Report", 105, 70, { align: "center" });

      let startY = 80;
      doc.setFontSize(12);

      // Table Row: BMI
      doc.setFillColor(220, 220, 220);
      doc.rect(20, startY, 50, 10, "F");
      doc.setTextColor(0);
      doc.text("Your BMI", 22, startY + 7);
      doc.rect(70, startY, 120, 10);
      doc.text(`${lastBMI}`, 75, startY + 7);

      // Table Row: Category
      startY += 12;
      doc.setFillColor(220, 220, 220);
      doc.rect(20, startY, 50, 10, "F");
      doc.setTextColor(0);
      doc.text("Category", 22, startY + 7);

      doc.setFillColor(tips[lastCategory].color);
      doc.rect(70, startY, 120, 10, "F");
      doc.setTextColor(255, 255, 255);
      doc.text(lastCategory, 75, startY + 7);

      // Reset text color
      doc.setTextColor(0);

      // Suggestions
      doc.setFont("helvetica", "bold");
      doc.text("Health Suggestions", 20, startY + 25);
      doc.setFont("helvetica", "normal");
      tips[lastCategory].list.forEach((t, i) => {
        doc.text(`- ${t}`, 25, startY + 35 + i * 8);
      });

      doc.save("BMI_Report.pdf");
    });
  }

  // 2. Health Tracker PDF
  if (downloadTracker) {
    downloadTracker.addEventListener("click", () => {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      addHeaderFooter(doc, "Weekly Health Tracker");

      const header = ["Day", "Weight", "Steps", "Calories", "Water", "Notes"];
      const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

      doc.setFontSize(12);
      doc.text("Weekly Tracker:", 20, 40);

      let startY = 50;
      doc.setFont("helvetica", "bold");
      header.forEach((h, i) => {
        doc.text(h, 20 + i * 30, startY);
      });

      doc.setFont("helvetica", "normal");
      days.forEach((d, row) => {
        let y = startY + (row + 1) * 10;
        doc.text(d, 20, y);
        header.slice(1).forEach((_, i) => {
          doc.text("____", 50 + i * 30, y);
        });
      });

      doc.save("Health_Tracker.pdf");
    });
  }

  // 3. Diet Plan PDF
  if (downloadDiet) {
    downloadDiet.addEventListener("click", () => {
      if (!lastCategory) return alert("Please calculate BMI first!");

      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      addHeaderFooter(doc, "Diet Plan");

      doc.setFontSize(12);
      doc.text(`Category: ${lastCategory}`, 20, 40);

      let diet = [];
      if (lastCategory === "Underweight") {
        diet = [
          "Eat calorie-dense foods (nuts, dairy, rice).",
          "Add protein shakes or smoothies.",
          "Have frequent meals (5–6 times/day)."
        ];
      } else if (lastCategory === "Normal weight") {
        diet = [
          "Maintain a balanced plate (carbs, proteins, fats).",
          "Stay hydrated.",
          "Continue regular exercise."
        ];
      } else if (lastCategory === "Overweight") {
        diet = [
          "Focus on calorie deficit.",
          "Eat more vegetables and lean protein.",
          "Avoid sugar-sweetened drinks."
        ];
      } else {
        diet = [
          "Avoid fried and processed foods.",
          "Eat high-fiber, low-calorie meals.",
          "Consult a dietitian for a structured plan."
        ];
      }

      doc.setFont("helvetica", "bold");
      doc.text("Diet Recommendations:", 20, 60);
      doc.setFont("helvetica", "normal");
      diet.forEach((d, i) => {
        doc.text(`- ${d}`, 25, 70 + i * 10);
      });

      doc.save("Diet_Plan.pdf");
    });
  }
});
