// bmiReport.js
// Handles BMI Report PDF download

function addHeaderFooter(doc, title) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("GYM‖BMI", 20, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(title, 105, 15, { align: "center" });
  const now = new Date().toLocaleString();
  doc.setFontSize(10);
  doc.text(`Generated: ${now}`, 200, 15, { align: "right" });
  doc.setDrawColor(150);
  doc.line(20, 20, 190, 20);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("Confidential | Generated by BMI Calculator – GYM‖BMI", 105, 285, { align: "center" });
  doc.setTextColor(0);
}

function generateBMIReport() {
  if (typeof lastBMI === 'undefined' || !lastBMI || typeof lastCategory === 'undefined') {
    alert("Please calculate BMI first!");
    return;
  }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  addHeaderFooter(doc, "BMI & Body Composition Report");

  const age = lastAge ?? "N/A";
  const gender = lastGender ?? "N/A";
  const dob = lastDOB ?? "N/A";
  const height = document.getElementById("height").value;
  const weight = document.getElementById("weight").value;

  doc.setFontSize(12);
  doc.text(`Name: ${lastName}`, 20, 30);
  doc.text(`DOB: ${dob}`, 20, 37);
  doc.text(`Age: ${age}`, 20, 44);
  doc.text(`Gender: ${gender}`, 20, 51);
  doc.text(`Height: ${height} cm`, 120, 30);
  doc.text(`Weight: ${weight} kg`, 120, 37);
  doc.setTextColor(tips[lastCategory].color);
  doc.text(`BMI: ${lastBMI} (${lastCategory})`, 120, 44);
  doc.setTextColor(0);

  // Body composition estimates
  const bodyFat = (1.2 * lastBMI + 0.23 * age - 16.2).toFixed(1);
  const muscleMass = (weight * 0.4).toFixed(1);
  const waterPercentage = (weight * 0.6).toFixed(1);

  doc.setFont("helvetica", "bold");
  doc.text("Estimated Body Composition:", 20, 70);
  doc.setFont("helvetica", "normal");
  doc.text(`Body Fat %: ${bodyFat}%`, 20, 80);
  doc.text(`Muscle Mass: ${muscleMass} kg`, 20, 87);
  doc.text(`Water Weight: ${waterPercentage} kg`, 20, 94);

  // Analysis
  doc.setFont("helvetica", "bold");
  doc.text("Health Analysis:", 20, 110);
  doc.setFont("helvetica", "normal");
  const analysis = {
    "Underweight": "You are below the healthy range. Focus on nutrient-rich and calorie-dense foods.",
    "Normal weight": "You are in the healthy range. Maintain balanced diet and regular exercise.",
    "Overweight": "You are above the healthy range. Start mild exercise and control calorie intake.",
    "Obesity": "You are in the high-risk category. Consult a healthcare provider for a structured plan."
  };
  doc.text(analysis[lastCategory], 20, 120, { maxWidth: 170 });

  // Tips
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Tips:", 20, 150);
  doc.setFont("helvetica", "normal");
  tips[lastCategory].list.forEach((tip, i) => {
    doc.text(`- ${tip}`, 20, 160 + i * 7);
  });

  doc.save("BMI_Report_by_GYMBMI.pdf");
}

window.generateBMIReport = generateBMIReport;

