// dietPlan.js
// Handles BMI Diet Plan PDF download

function addHeaderFooter(doc, title) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("GYM‖BMI", 20, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(title, 105, 15, { align: "center" });
  const now = new Date().toLocaleString();
  doc.setFontSize(10);
  doc.text(`Generated: ${now}`, 200, 15, { align: "right" });
  doc.setDrawColor(150);
  doc.line(20, 20, 190, 20);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("Confidential | Generated by BMI Calculator – GYM‖BMI", 105, 285, { align: "center" });
  doc.setTextColor(0);
}

function generateDietPlan() {
  if (typeof lastCategory === 'undefined' || !lastCategory) {
    alert("Please calculate BMI first!");
    return;
  }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  addHeaderFooter(doc, "Personalized Diet Plan");

  doc.setFontSize(12);
  doc.text(`Category: ${lastCategory}`, 20, 30);
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Daily Diet Plan:", 20, 50);
  doc.setFont("helvetica", "normal");

  const plans = {
    "Underweight": [
      "Breakfast: Oats with milk, nuts, banana",
      "Mid-Morning: Peanut butter sandwich / smoothie",
      "Lunch: Rice, chicken/fish, veggies",
      "Snack: Dry fruits / protein shake",
      "Dinner: Pasta/chapati with paneer/veg curry",
      "Before Bed: Warm milk with honey"
    ],
    "Normal weight": [
      "Breakfast: Eggs, toast, fruits",
      "Mid-Morning: Seasonal fruit",
      "Lunch: Quinoa/brown rice + dal + salad",
      "Snack: Handful of nuts",
      "Dinner: Chapati + dal + veggies",
      "Before Bed: Herbal tea"
    ],
    "Overweight": [
      "Breakfast: Oatmeal + apple",
      "Mid-Morning: Buttermilk / fruit",
      "Lunch: Salad bowl with lean protein",
      "Snack: Roasted chana, sprouts",
      "Dinner: Soup + grilled veggies + chapati",
      "Before Bed: Green tea"
    ],
    "Obesity": [
      "Breakfast: Veg omelet / smoothie",
      "Mid-Morning: Apple / pear",
      "Lunch: Steamed veggies + dal/soup",
      "Snack: Nuts in small portions",
      "Dinner: Veg soup + chapati",
      "Before Bed: Herbal tea (no sugar)"
    ]
  };

  let y = 65;
  plans[lastCategory].forEach((meal, i) => {
    doc.text(`${i + 1}. ${meal}`, 20, y);
    y += 10;
  });

  doc.save("Diet_Plan_by_GYMBMI.pdf");
}

window.generateDietPlan = generateDietPlan;

